<br />

<label>Username:</label> <?php echo $this->details['username'] ?><br />
<label>Email:</label> <?php echo $this->details['email'] ?><br />

<form method="post">

    <?php $this->renderTemplate('sections/_errors.phtml') ?>
    <div class="info"><?php echo $this->message ?></div>

    <label>Password</label> <input type="password" name="password" value="" /><br />
    <label>Password Again</label> <input type="password" name="password_check" value="" /><br />
    <input type="submit" name="updatepw" value="Create User" />
</form>